# Generated by Django 2.2.12 on 2020-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Infulencing is an art'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
